M48
; DRILL file {KiCad (6.0.11)} date Fri Aug 21 12:38:23 2026
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-21T12:38:23+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0433
%
G90
G05
T1
X4.5449Y-3.4
X4.7417Y-3.4
X5.2343Y-3.3585
X5.4311Y-3.3585
X5.7Y-3.5
X5.7Y-3.9
T2
X5.25Y-3.8
X5.35Y-3.8
T3
X3.6Y-3.4
X4.9584Y-3.4072
X5.7Y-3.3
T4
X3.8Y-3.4
X4.2Y-3.4
X4.8Y-3.0106
X4.9Y-3.0106
X5.0Y-3.0106
T0
M30
